### ISSUE TITLE
No tars/tars.MD file

### ISSUE THREAD

**Issue by hrishikeshrt** [indic-dict/stardict-marathi#1]
Most of the other dictionaries have `tars/tars.MD` in `gh-pages`, but this one doesn't seem to have that

**Comment by vvasuki** [comment]
Thanks for pointing it out. The automated build should have failed and alerted me, but it didn't ( https://github.com/indic-dict/dict-tools/issues/2 ).

Looks like the dictionary building script is not getting GITHUB_TOKEN . Strangely, https://github.com/indic-dict/stardict-marathi/blob/master/.github/workflows/build.yml seems identical to https://github.com/indic-dict/stardict-sanskrit-vyAkaraNa/blob/master/.github/workflows/build.yml , where the build is succeeding. So, not sure what's happening.

**Comment by vvasuki** [comment]
Solved now.
